// HR27 scanner. Verdrahtet in scan-audit-categories.ts (buildAuditConfig ->
// Kategorie 'audit-hr27') und direkt getestet in tests/write/scanner-c10.spec.ts.
// Limits/Skip-Liste sind per Cross-Test (tests/write/hr27-lines-check.spec.ts)
// mit scripts/hr27-lines-baseline.json gepinnt — bei Aenderung beide Seiten ziehen.
import fs from 'node:fs'
import path from 'node:path'

export interface Hr27Finding {
  path: string
  ext: string
  lines: number
  limit: number
  overshoot: number
}

export const HR27_LIMITS: Record<string, number> = {
  js: 300,
  ts: 300,
  jsx: 300,
  tsx: 300,
  mjs: 300,
  cjs: 300,
  php: 300,
  py: 500,
  css: 300,
  scss: 300,
  sass: 300,
  less: 300,
  html: 250,
  htm: 250,
  vue: 400,
  svelte: 400,
  astro: 400,
}

export const HR27_SKIP_DIRS = new Set([
  '.git',
  'vendor',
  'node_modules',
  'dist',
  'dist-release',
  'out',
  'build',
  '.next',
  'target',
  'migrations',
  'seeds',
  'memory',
  'agent-memory',
  // Runtime-/Evidenzartefakte sind per .gitignore nicht versionierter Output.
  'audit-runtime',
])

const PLAN_RX = /^(PLAN|COMPLETED_PLAN|SUPERSEDED_PLAN|WIP_PLAN|DRAFT_PLAN)-.*\.md$/i
const GENERATED_RX = /auto-generated|@generated|generated by|this file is generated/i

export function scanHr27(rootDir: string): Hr27Finding[] {
  const findings: Hr27Finding[] = []
  walk(rootDir, rootDir, findings)
  return findings.sort((a, b) => a.path.localeCompare(b.path))
}

function walk(rootDir: string, currentDir: string, findings: Hr27Finding[]): void {
  let entries: fs.Dirent[]
  try {
    entries = fs.readdirSync(currentDir, { withFileTypes: true })
  } catch {
    return
  }
  for (const entry of entries) {
    const abs = path.join(currentDir, entry.name)
    if (entry.isDirectory()) {
      if (!shouldSkipDir(rootDir, abs, entry.name)) walk(rootDir, abs, findings)
      continue
    }
    if (entry.isFile()) scanFile(abs, findings)
  }
}

function shouldSkipDir(rootDir: string, abs: string, name: string): boolean {
  if (HR27_SKIP_DIRS.has(name.toLowerCase())) return true
  const rel = toRel(rootDir, abs).toLowerCase().replace(/\\/g, '/')
  return rel === '.claude/docs' || rel.startsWith('.claude/docs/')
}

function scanFile(abs: string, findings: Hr27Finding[]): void {
  const ext = path.extname(abs).slice(1).toLowerCase()
  const limit = HR27_LIMITS[ext]
  if (!limit || shouldSkipFile(abs)) return
  const text = readText(abs)
  if (text === null || GENERATED_RX.test(text.slice(0, 4096))) return
  const lines = countLines(text)
  if (lines <= limit) return
  findings.push({ path: abs, ext, lines, limit, overshoot: lines - limit })
}

function shouldSkipFile(abs: string): boolean {
  const base = path.basename(abs)
  const lower = base.toLowerCase()
  return lower === 'memory.md' || PLAN_RX.test(base)
}

function readText(abs: string): string | null {
  try {
    return fs.readFileSync(abs, 'utf8')
  } catch {
    return null
  }
}

function countLines(text: string): number {
  if (text.length === 0) return 0
  const normalized = text.endsWith('\n') ? text.slice(0, -1) : text
  return normalized.length === 0 ? 1 : normalized.split(/\r?\n/).length
}

function toRel(rootDir: string, abs: string): string {
  return path.relative(rootDir, abs) || '.'
}
